# Default values

replicaCount: 1

image:
  repository: eeacms/lpd
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceUrl: https://lpd.eea.europa.eu

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

dbconnectionUrl: replaceme
dbconnectionUsername: replaceme
dbconnectionPassword: replaceme

lpdExtractSpatialDataService: replaceme
lpdPrintService: replaceme
lpdSearchLayer: replaceme

mailSmtpHost: replaceme
mailSmtpUser: ''
defaultMailAddress: replaceme

sckAuth: replaceme
sckBackgroundLayer: replaceme

sckBeneficiaryAccessActivationTokenValidity: '10'
sckBeneficiaryAccessValidity: '180'
sckBeneficiaryFeatureLayerUrl: replaceme
sckBeneficiaryPublicLayer: replaceme
sckBingKey: replaceme

sckLdapBaseContext: replaceme
sckLdapUid: uid=
sckLdapUrl: replaceme

sckMailOutcopy: ""
sckMailQc: ""
sckMailStmpFromForBenef: ""
sckReportSupportMail: ""
sckShapefileImportServiceUrl: replaceme
sckSpatialReference: '3857'
sckSuperAdmin: replaceme
sckTablePrefix: LPD_2020.DBO

timezone: Europe/Copenhagen

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/app-root: /lpd_web/pages/login/beneficiary.xhtml
  hosts:
    - host: lpd.eea.europa.eu
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ''
      hosts:
        - lpd.eea.europa.eu

resources:
  requests:
    memory: 256Mi
  limits:
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

nextcloud:
  image: eeacms/nextcloud:25.0.6-apache
  adminPassword: replaceme
  adminUser: replaceme
  # What is trustedProxies for?
  trustedProxies: replaceme
  securityContext: {}
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 1Gi

  ingress:
    enabled: false
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers 'X-XSS-Protection: 1; mode=block'
          'X-Content-Type-Options: nosniff'
          'X-Robots-Tag: noindex, nofollow'
          'X-Frame-Options: SAMEORIGIN'
          'Referrer-Policy: no-referrer';
      nginx.ingress.kubernetes.io/server-snippet: |
        location /.well-known/carddav {
          rewrite ^/.well-known/carddav?$ /remote.php/dav break;
        }
        location /.well-known/caldav {
          rewrite ^/.well-known/caldav?$ /remote.php/dav break;
        }
        location /.well-known/webfinger {
          rewrite ^/.well-known/webfinger?$ /index.php/.well-known/webfinger break;
        }
    hosts:
      - host: lpddata.eea.europa.eu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ''
        hosts:
          - lpddata.eea.europa.eu

cron:
  securityContext: {}
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 1Gi

