apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dpl-volto
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: volto

spec:
  replicas: {{ .Values.volto.replicaCount }}
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: volto

  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: volto
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}
      containers:
      - name: volto
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
        - name: PORT
          value: "3000"
        - name: RAZZLE_SENTRY_RELEASE
          value: "{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: RAZZLE_FRONTEND_VERSION
          value: "{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: SENTRY_RELEASE
          value: "{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        {{- range $key, $value := .Values.volto.environment }}
        {{- if ($value) }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}

        ports:
        - containerPort: 3000

        {{- if (.Values.volto.livenessProbe) }}
        livenessProbe:
          {{- toYaml .Values.volto.livenessProbe | nindent 10 }}
        {{- end }}

        {{- if (.Values.volto.startupProbe) }}
        startupProbe:
          {{- toYaml .Values.volto.startupProbe | nindent 10 }}
        {{- end }}

        {{- if (.Values.volto.readinessProbe) }}
        readinessProbe:
          {{- toYaml .Values.volto.readinessProbe | nindent 10 }}
        {{- end }}

        resources:
          {{- toYaml .Values.volto.resources | nindent 10 }}

      {{- with .Values.volto.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volto.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volto.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always

