apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: apache
  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: apache
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}

      initContainers:
      # Set up ssl.conf and nc.conf
      - name: init-ssl-conf
        image: busybox:1.36
        command: ['sh', '-c', 'cp /mnt/ssl.conf /usr/local/apache2/conf/extra/ssl.conf && touch /usr/local/apache2/conf/extra/nc.conf']
        volumeMounts:
        - mountPath: /usr/local/apache2/conf/extra
          name: sdi-apache-configuration
        - mountPath: /mnt/ssl.conf
          name: sdi-apache-config
          readOnly: true
          subPath: ssl.conf

      containers:
      - name: apache
        image: eeacms/sdi-apache:1.0.13
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: SERVERADMIN
          value: "{{ .Values.apache.serverAdmin }}"
        - name: SERVERNAME
          value: "{{ .Values.serverName }}"
        resources:
          {{- toYaml .Values.apache.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /usr/local/apache2/conf/extra
          name: sdi-apache-configuration

        - mountPath: /usr/local/apache2/htdocs
          name: sdi-apache-www
        - mountPath: /var/local/gis_sdi
          name: gis-sdi
          readOnly: true
        - mountPath: /var/log/apache/logs
          name: sdi-apache-log
        - mountPath: /ssl/server.key
          name: eea-certificate
          readOnly: true
          subPath: tls.key
        - mountPath: /ssl/server.crt
          name: eea-certificate
          readOnly: true
          subPath: tls.crt
        - mountPath: /ssl/ca-bundle.crt
          name: ca-certificates
          readOnly: true
          subPath: ca-bundle.crt
        - mountPath: /ssl/chain.crt
          name: ca-certificates
          readOnly: true
          subPath: chain.crt

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      volumes:
      - name: sdi-apache-configuration
        persistentVolumeClaim:
          claimName: sdi-apache-configuration
      - name: sdi-apache-www
        persistentVolumeClaim:
          claimName: sdi-apache-www
      - name: sdi-apache-log
        persistentVolumeClaim:
          claimName: sdi-apache-log
      - name: gis-sdi
        persistentVolumeClaim:
          claimName: gis-sdi
          readOnly: true

      - name: eea-certificate
        secret:
          defaultMode: 0444
          optional: false
          secretName: "{{ .Values.serverCert }}"
      - name: ca-certificates
        configMap:
          defaultMode: 0444
          optional: false
          name: {{ .Release.Name }}-cacrts
      - name: sdi-apache-config
        configMap:
          defaultMode: 0444
          optional: false
          name: sdi-apache-config
