apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: advisory-board-admin
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: advisory-board-admin
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /VirtualHostBase/https/{{ .Values.plone.hostname }}:443/advisory/VirtualHostRoot/_vh_admin/$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.plone.hostname }}
    http:
      paths:
      - path: /admin(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.varnish.serviceName }}
            port:
              number: { .Values.varnish.port }}
      - path: /google85dc6cec8f1329e5.html(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.varnish.serviceName }}
            port:
              number: { .Values.varnish.port }}
      - path: /.well-known/microsoft-identity-association.json(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.varnish.serviceName }}
            port:
              number: {{ .Values.varnish.port }}
  {{- if .Values.ingress.certificate }}
  tls:
  - hosts:
    - {{ .Values.plone.hostname }}
    secretName: {{ .Values.ingress.certificate }}
  {{- end  }}
   
