{{- if  .Values.debug.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dpl-debug
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: debug

spec:
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: debug

  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: debug
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}
      containers:
      - name: debug
        image: eeacms/advisory-board-backend-devel
        imagePullPolicy: Always
        args:
        - cat
        env:
        - name: SERVER_NAME
          value: "{{ .Values.plone.hostname }}"
        - name: SENTRY_SITE
          value: "{{ .Values.plone.hostname }}"
        - name: GRAYLOG_FACILITY
          value: "{{ .Values.plone.hostname }}"
        - name: BACKEND_VERSION
          value: "{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: SENTRY_RELEASE
          value: "{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        - name: RELSTORAGE_DSN
          value: "host='postgres' dbname='{{ .Values.plone.database.POSTGRES_DB }}' user='{{ .Values.plone.database.POSTGRES_USER }}' password='{{ .Values.plone.database.POSTGRES_PASSWORD }}'"
        {{- range $key, $value := .Values.plone.environment }}
        {{- if ($value) }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}

        ports:
        - containerPort: 8080

        stdin: true
        tty: true


        resources:
          {{- toYaml .Values.plone.resources | nindent 10 }}

      {{- with .Values.plone.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.plone.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.plone.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
{{- end }}
