# Default values

image:
  repository: andreicenja/docker-nessus_scanner
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # Only to be used for testing new container images.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

linkingKey: ""

scannerName: ""

adminName: ""

adminPwd: ""

listentoHostport: false

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}
# requests:
#   memory: 1Gi
# limits:
#   memory: 1300Mi

nodeSelector: {}

tolerations: []

affinity: {}
